---

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lidarr_cloudflare_api_token }}'
    zone: '{{ lidarr_cloudflare_zone }}'
    state: absent
    type: CNAME
    record: '{{ lidarr_cloudflare_record }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lidarr_cloudflare_api_token }}'
    zone: '{{ lidarr_cloudflare_zone }}'
    state: absent
    type: A
    record: '{{ lidarr_cloudflare_record }}'

- name: Get public ip for DNS tasks
  block:
    - name: Get public IP
      community.general.ipify_facts:
        timeout: 20
      delegate_to: localhost
      register: public_ip

    - name: Public IP output
      ansible.builtin.debug:
        msg: '{{ ipify_public_ip }}'

- name: Add lidarr DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lidarr_cloudflare_api_token }}'
    zone: '{{ lidarr_cloudflare_zone }}'
    state: present
    solo: true
    proxied: '{{ lidarr_cloudflare_proxy }}'
    type: '{{ lidarr_cloudflare_record_type }}'
    value: '{{ ipify_public_ip }}'
    record: '{{ lidarr_cloudflare_record }}'
  register: lidarr_cloudflare_record_creation_status

- name: Tasks on success
  when: lidarr_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        lidarr_cloudflare_record_print: '{{ (lidarr_cloudflare_record == lidarr_cloudflare_zone) | ternary(lidarr_cloudflare_zone, lidarr_cloudflare_record + "." + lidarr_cloudflare_zone) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ lidarr_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ lidarr_cloudflare_proxy }}'
